version: '3.9'

services:
  mcp-server-bigquery:
    build: .
    container_name: mcp-server-bigquery
    ports:
      - "${PORT:-8085}:8085"
    environment:
      - BIGQUERY_PROJECT=${BIGQUERY_PROJECT:-data-warehouse-414312}
      - BIGQUERY_LOCATION=${BIGQUERY_LOCATION:-europe-west4}
      - BIGQUERY_KEY_FILE=${BIGQUERY_KEY_FILE:-}

    volumes:
      - ./src:/app/src
      - ./secrets:/app/src/secrets
