version: '3.9'

services:
  mcp-server-bigquery:
    build: .
    container_name: mcp-server-bigquery
    ports:
      - "8085:8085"
    environment:
      - BIGQUERY_PROJECT="data-warehouse-414312"
      - BIGQUERY_LOCATION="europe-west4"
      - BIGQUERY_KEY_FILE=secrets/data-warehouse-414312-a4116c865c13.json

    volumes:
      - ./src:/app/src
      - ./secrets:/app/src/secrets
